### PR TITLE
Merge ankit source code

### PR DESCRIPTION
**Pull request by TroJan**
Regarding Issue #5

### CODE REVIEW

**Comment by TroJan** [comment]
declining this PR here since there are merge conflicts which cant be merged.

Solution: Manually merging into master branch.

**Comment by ankitjain28may** [comment]
Ok sir I wl do that

**Comment by TroJan** [comment]
@ankitjain28may : I will have to do it. Will update you shortly.

**Comment by ankitjain28may** [comment]
Ok sir

**Pull request closed without merging**
